apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: node-test-app-rs
  labels:
    app: node-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template: 
    metadata:
      labels:
        app: node
    spec: 
      containers:
        - name: node-test-web 
          image: muralisocial123/node-test-app:latest
          ports:
            - containerPort: 80      
